# Generated by Django 4.1.4 on 2023-01-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todopro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
