# Generated by Django 4.1.4 on 2023-01-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todopro', '0002_todos_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='day',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
